apiVersion: v1
kind: Service
metadata:
  name: go-svc
spec:
  selector:
    app: go-app
  type: {{ .Values.service.type}}                      # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080